---
- name: install base
  apt: name={{ item }} state=present update_cache=yes
  with_items: "{{ general_packages }}"
  tags: packages

- name: install base shell editors
  apt: name={{ item }} state=present update_cache=yes
  with_items: "{{ shell_editors }}"
  tags: packages, editors

- name: configure unattended updates
  template: src=50unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades owner=root group=root
  tags: updates

- name: check if current timezone exists
  lineinfile: dest=/etc/timezone state=present line="{{ homebase_timezone }}"

- name: enable ntp
  service: name=ntp enabled=yes
  tags: timezone

- name: start ntp
  service: name=ntp state=started
  tags: timezone
