---
- name: install development tools
  yum: name="@Development tools" state=present
  tags: packages

- name: install base
  yum: name={{ item }} state=present update_cache=yes
  with_items: "{{ general_packages }}"
  tags: packages

- name: install base shell editors
  yum: name={{ item }} state=present update_cache=yes
  with_items: "{{ shell_editors }}"
  tags: packages, editors

- name: install automatic updates
  yum: name=yum-cron state=present update_cache=yes
  tags: updates

- name: add update configuration
  template: src=yum-cron.conf dest=/etc/yum/yum-cron.conf owner=root group=root
  tags: updates

- name: activate cron updates
  sudo: yes
  shell: chkconfig --level 345 yum-cron on
  notify: start yum cron
  tags: updates

- name: configure timezone
  sudo: yes
  shell: timedatectl set-timezone {{ homebase_timezone }}
  tags: timezone

- name: enable ntp
  service: name=ntpd enabled=yes
  tags: timezone

- name: start ntp
  service: name=ntpd state=started
  tags: timezone

- name: allocate space for swap
  sudo: yes
  shell: fallocate -l {{ homebase_swapsize }} /swapfile creates=/swapfile
  tags: swapfile

- name: set permissions on swap
  file: path=/swapfile mode=600
  tags: swapfile

# - name: make swap
#   sudo: yes
#   shell: mkswap /swapfile && swapon /swapfile
#   tags: swapfile
#
# - name: make swap boot on startup
#   sudo: yes
#   shell: sh -c 'echo "/swapfile none swap sw 0 0" >> /etc/fstab'
#   tags: swapfile
