---
- name: install development tools
  yum: name="@Development tools" state=present
  tags: packages

- name: install base
  yum: name={{ item }} state=present update_cache=yes
  with_items: "{{ general_packages }}"
  tags: packages

- name: install base shell editors
  yum: name={{ item }} state=present update_cache=yes
  with_items: "{{ shell_editors }}"
  tags: packages, editors

- name: install automatic updates
  yum: name=yum-cron state=present update_cache=yes
  tags: updates

- name: add update configuration
  template: src=yum-cron.conf dest=/etc/yum/yum-cron.conf owner=root group=root
  tags: updates

- name: start yum cron
  service: name=yum-cron state=started

- name: check timezone
  shell: timedatectl status | grep -ci "{{ homebase_timezone }}"
  register: timezone_check
  ignore_errors: true
  tags: timezone

- name: configure timezone
  sudo: yes
  shell: timedatectl set-timezone {{ homebase_timezone }}
  when: timezone_check | failed
  tags: timezone

- name: enable ntp
  service: name=ntpd enabled=yes
  tags: timezone

- name: start ntp
  service: name=ntpd state=started
  tags: timezone
