---
- name: start yum cron
  service: name=yum-cron state=started

- name: restart yum cron
  service: name=yum-cron state=restarted

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
